import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Box, CssBaseline } from "@mui/material";
import Sidebar from "@/components/Sidebar";
import { ThemeProviderWrapper } from "@/theme/theme";
import { QueryProvider } from "../QueryProvider";
import { LocalizationProviderComponent } from "../LocalizationProvider";
import { auth } from "@/auth";
import { Toolbar } from "@/components/Toolbar";
import { signout } from "../lib/actions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Huji Job System",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProviderWrapper>
            <QueryProvider>
              <LocalizationProviderComponent>
                <Box sx={{ display: "flex", flexDirection: "column" }}>
                  <Toolbar session={session} />
                  <Box sx={{ display: "flex" }}>
                    <CssBaseline />
                    {/* {(session && session.user.role === "Admin") && <Sidebar />} */}
                    <Box component="main" sx={{ flexGrow: 1, p: 3 }}>
                      {children}
                    </Box>
                  </Box>
                </Box>
              </LocalizationProviderComponent>
            </QueryProvider>
          </ThemeProviderWrapper>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
